export const AUTH_TYPES = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",
  RESET_LOGIN_ERRORS: "RESET_LOGIN_ERRORS",

  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  RESET_REGISTER_ERRORS: "RESET_REGISTER_ERRORS",

  VERIFY_ACCOUNT_START: "VERIFY_ACCOUNT_START",
  VERIFY_ACCOUNT_SUCCESS: "VERIFY_ACCOUNT_SUCCESS",
  VERIFY_ACCOUNT_FAILURE: "VERIFY_ACCOUNT_FAILURE",

  RESEND_OTP_START: "RESEND_OTP_START",
  RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",
  RESEND_OTP_FAILURE: "RESEND_OTP_FAILURE",
  CLEAR_OTP_ERRORS: "CLEAR_OTP_ERRORS",

  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",

  CHECK_AUTH_START: "CHECK_AUTH_START",
  CHECK_AUTH_END: "CHECK_AUTH_END",
  SET_AUTH_CHECKED: "SET_AUTH_CHECKED",
  RESET_AUTH_ERRORS: "RESET_AUTH_ERRORS",

  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  CHANGE_PASSWORD_START: "CHANGE_PASSWORD_START",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  RESET_CHANGE_PASSWORD: "RESET_CHANGE_PASSWORD",

  DELETE_ACCOUNT_START: "DELETE_ACCOUNT_START",
  DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_FAILURE: "DELETE_ACCOUNT_FAILURE",
  RESET_DELETE_ACCOUNT: "RESET_DELETE_ACCOUNT",

  RESET_MY_ADVERTISEMENTS: "RESET_MY_ADVERTISEMENTS",
  RESET_FAVORITES: "RESET_FAVORITES",
  RESET_PROFILE: "RESET_PROFILE",
  RESET_SUBSCRIPTION: "RESET_SUBSCRIPTION",
};
